---
- name: set up hugo
  apt:
    pkg:
      - nodejs
      - npm
      - hugo
      - git-lfs
      # XXX
      # - node-postcss-cli
- name: git helpers
  apt:
    pkg:
      - gh
      - ruby-gitlab
- name: documentation helpers
  apt:
    pkg:
      - zeal
- name: haskell dev tools
  apt:
    pkg:
      - haskell-stack
      - libncurses-dev  # Needed for "hack hoogle"
- name: Extra docs
  apt:
    pkg:
      - perl-doc
      - bash-doc
      - make-doc
- name: VM and docker
  apt:
    pkg:
      - virt-manager
      - docker.io

- name: Linter
  apt:
    pkg:
      - shellcheck

- name: Python stuff
  apt:
    pkg:
      - python3-poetry
      - pipx
      - python3-pylsp
      - python3-click
      - python3-xdg
      - python3-yaml
