---
- name: set up hugo
  apt:
    pkg:
      - hugo
      - git-lfs
      # XXX
      # - node-postcss-cli
- name: git helpers
  apt:
    pkg:
      - gh
      - ruby-gitlab
- name: documentation helpers
  apt:
    pkg:
      - zeal
- name: haskell dev tools
  apt:
    pkg:
      - haskell-stack
      - libncurses-dev  # Needed for "hack hoogle"
- name: Perl docs
  apt:
    pkg:
      - perl-doc
