---
# tasks file for gui
- name: install flatpak snapd nix
  apt:
    pkg:
      - snapd
      - flatpak
      - nix-setup-systemd
- name: install standard KDE desktop
  apt:
    pkg:
      - task-kde-desktop
      - plasma-discover-backend-flatpak
- import_tasks: fonts.yml
- import_tasks: emacs.yml
- import_tasks: games.yml
- import_tasks: dev.yml
