---
# tasks file for gui
- name: install flatpak snapd nix
  apt:
    pkg:
      - snapd
      - flatpak
      - nix-setup-systemd

# XXX Might be better as a custom fact collector.
- name: Check if snaps are held
  command: snap refresh --time
  register: snap_refresh
  changed_when: False
- name: Register if snaps are held fact
  changed_when: False
  set_fact:
    snaps_held: "{% if 'hold: forever' in snap_refresh.stdout %}True{% else %}False{% endif %}"
- name: Ensure snaps do not auto update
  command: snap refresh --hold
  when: not snaps_held

- name: add flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
- name: install Signal
  community.general.flatpak:
    name: org.signal.Signal
    remote: flathub
- name: Install tor
  apt:
    pkg:
      - torbrowser-launcher
- name: Disable tor service because using the launcher
  service:
    name: tor
    enabled: false
    state: stopped
- name: Enable touchscreen scrolling in Firefox
  copy:
    content: |
      # https://superuser.com/questions/1151161/enable-touch-scrolling-in-firefox
      MOZ_USE_XINPUT2=1
    dest: /etc/environment.d/91-firefox-touchscreen.conf
- name: install standard KDE desktop
  apt:
    pkg:
      - task-kde-desktop
      - plasma-discover-backend-flatpak
      # See https://wiki.debian.org/PipeWire
      # Make sure to run "systemctl --user --now enable wireplumber.service"
      # Also required to screenshare in Wayland.
      - wireplumber
      - libspa-0.2-bluetooth  # Makes bluetooth audio work.

      - syncthingtray-kde-plasma
      - kdiskmark
- name: install extras
  apt:
    pkg:
      - chromium
      - weechat-curses
      - obs-studio
      - audacity
      - openvpn
      # Local dictionary
      - dict-elements
      - dict-foldoc
      - dict-gcide
      - dict-vera
      - dict-freedict-eng-spa
      - dict-freedict-spa-eng
      - dictd
      - dict
      # Resume
      - pandoc
      - texlive-full
      # Publishing
      - inkscape
      - gimp
      - scribus
- import_tasks: fonts.yml
- import_tasks: emacs.yml
- import_tasks: games.yml
- import_tasks: dev.yml
