---
# tasks file for gui
- name: install flatpak snapd nix
  apt:
    pkg:
      - snapd
      - flatpak
      - nix-setup-systemd
- name: add flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
- name: install Signal
  community.general.flatpak:
    name: org.signal.Signal
    remote: flathub
- name: install standard KDE desktop
  apt:
    pkg:
      - task-kde-desktop
      - plasma-discover-backend-flatpak
      # See https://wiki.debian.org/PipeWire
      # Make sure to run "systemctl --user --now enable wireplumber.service"
      # Also required to screenshare in Wayland.
      - wireplumber
      - libspa-0.2-bluetooth  # Makes bluetooth audio work.

      - kdiskmark
- name: install extras
  apt:
    pkg:
      - chromium
      - weechat-curses
      - obs-studio
      - audacity
      - openvpn
      # Local dictionary
      - dict-elements
      - dict-foldoc
      - dict-gcide
      - dict-vera
      - dictd
      - dict
      # Resume
      - pandoc
      - texlive-full
- import_tasks: fonts.yml
- import_tasks: emacs.yml
- import_tasks: games.yml
- import_tasks: dev.yml
